#sopxs command copy UI
import tkinter as tk
import pyperclip
root = tk.Tk()
root.title('sopxs command copy UI.exe')
root.geometry('460x220')
A =False
B = False
C = False
D = False
E = False
F = False

def Ar():
    ui1A.place_forget()
    ui2A.place_forget()
    ui3A.place_forget()
    ui4A.place_forget()
    ui5A.place_forget()
    ui1B.place_forget()
    ui2B.place_forget()
    ui3B.place_forget()
    ui4B.place_forget()
    ui5B.place_forget()
    ui6B.place_forget()
    ui1C.place_forget()
    ui2C.place_forget()
    ui3C.place_forget()
    ui1D.place_forget()
    ui2D.place_forget()
    global A
    A = True
    if A:
        ui1A.place(x=115, y=0)
        ui2A.place(x=197, y=0)
        ui3A.place(x=115, y=30)
        ui4A.place(x=173, y=30)
        ui5A.place(x=231, y=30)
def Br():
    ui1A.place_forget()
    ui2A.place_forget()
    ui3A.place_forget()
    ui4A.place_forget()
    ui5A.place_forget()
    ui1B.place_forget()
    ui2B.place_forget()
    ui3B.place_forget()
    ui4B.place_forget()
    ui5B.place_forget()
    ui6B.place_forget()
    ui1C.place_forget()
    ui2C.place_forget()
    ui3C.place_forget()
    ui1D.place_forget()
    ui2D.place_forget()
    global B
    B = True
    if B:
        ui1B.place(x=115, y=0)
        ui2B.place(x=115,y=30)
        ui3B.place(x=115, y=60)
        ui4B.place(x=115, y=90)
        ui5B.place(x=115, y=120)
        ui6B.place(x=115, y=150)
def Cr():
    ui1A.place_forget()
    ui2A.place_forget()
    ui3A.place_forget()
    ui4A.place_forget()
    ui5A.place_forget()
    ui1B.place_forget()
    ui2B.place_forget()
    ui3B.place_forget()
    ui4B.place_forget()
    ui5B.place_forget()
    ui6B.place_forget()
    ui1C.place_forget()
    ui2C.place_forget()
    ui3C.place_forget()
    ui1D.place_forget()
    ui2D.place_forget()
    global C
    C = True
    ui1C.place(x=100, y = 0)
    ui2C.place(x=100, y=30)
    ui3C.place(x=100, y=60)
def Dr():
    ui1A.place_forget()
    ui2A.place_forget()
    ui3A.place_forget()
    ui4A.place_forget()
    ui5A.place_forget()
    ui1B.place_forget()
    ui2B.place_forget()
    ui3B.place_forget()
    ui4B.place_forget()
    ui5B.place_forget()
    ui6B.place_forget()
    ui1C.place_forget()
    ui2C.place_forget()
    ui3C.place_forget()
    ui1D.place_forget()
    ui2D.place_forget()
    global D
    D = True
    ui1D.place(x=100, y=0)
    ui2D.place(x=100, y=30)
def Er():
    ui1A.place_forget()
    ui2A.place_forget()
    ui3A.place_forget()
    ui4A.place_forget()
    ui5A.place_forget()
    ui1B.place_forget()
    ui2B.place_forget()
    ui3B.place_forget()
    ui4B.place_forget()
    ui5B.place_forget()
    ui6B.place_forget()
    ui1C.place_forget()
    ui2C.place_forget()
    ui3C.place_forget()
    ui1D.place_forget()
    ui2D.place_forget()
    global E
    E = True
def Fr():
    ui1A.place_forget()
    ui2A.place_forget()
    ui3A.place_forget()
    ui4A.place_forget()
    ui5A.place_forget()
    ui1B.place_forget()
    ui2B.place_forget()
    ui3B.place_forget()
    ui4B.place_forget()
    ui5B.place_forget()
    ui6B.place_forget()
    ui1C.place_forget()
    ui2C.place_forget()
    ui3C.place_forget()
    ui1D.place_forget()
    ui2D.place_forget()
    global F
    F = True
def fal_q():
    global A, B, C, D, E, F
    A = False
    B = False
    C = False
    D = False
    E = False
    F = False
    ui1A.place_forget()
    ui2A.place_forget()
    ui3A.place_forget()
    ui4A.place_forget()
    ui5A.place_forget()
    ui1B.place_forget()
    ui2B.place_forget()
    ui3B.place_forget()
    ui4B.place_forget()
    ui5B.place_forget()
    ui6B.place_forget()
    ui1C.place_forget()
    ui2C.place_forget()
    ui3C.place_forget()
    ui1D.place_forget()
    ui2D.place_forget()
button1 = tk.Button(root, text='    1    ', command=Ar)
button1.place(x=0, y=10)
button2 = tk.Button(root, text='    2    ', command=Br)
button2.place(x=0, y=40)
button3 = tk.Button(root, text='    3    ', command=Cr)
button3.place(x=0, y=70)
button4 = tk.Button(root, text='  更多  ', command=Dr)
button4.place(x=0, y=100)
button5 = tk.Button(root, text='    5    ', command=Er)
button5.place(x=0, y=130)
button6 = tk.Button(root, text='    6    ', command=Fr)
button6.place(x=0, y=160)
butq = tk.Button(root, text='UI初始化', command=fal_q)
butq.place(x=0, y=190)
ui1A = tk.Button(root, text='是否开机；是', command=lambda: pyperclip.copy('是'))
ui1A.place_forget()
ui2A = tk.Button(root, text='是否开机；否', command=lambda: pyperclip.copy('否'))
ui2A.place_forget()
ui3A = tk.Button(root, text='刷新系统', command=lambda: pyperclip.copy('刷新'))
ui4A = tk.Button(root, text='开机密码', command=lambda: pyperclip.copy('wgh1wangguanghua1234wgh246t2736427463723'))
ui5A = tk.Button(root, text='连接网络', command=lambda: pyperclip.copy('联网'))
ui1B = tk.Button(root, text='文件应用处理', command=lambda: pyperclip.copy('选择/打开'))
ui2B = tk.Button(root, text='在已经执行命令“选择/打开”的情况下，打开应用：随机数', command=lambda:pyperclip.copy('随机数'))
ui3B = tk.Button(root, text='在已经执行命令“选择/打开”的情况下，打开应用：闹钟', command=lambda:pyperclip.copy('闹钟'))
ui4B = tk.Button(root, text='在已经执行命令“选择/打开”的情况下，打开应用：年', command=lambda:pyperclip.copy('年'))
ui5B = tk.Button(root, text='在已经执行命令“选择/打开”的情况下，打开应用：浏览器', command=lambda:pyperclip.copy('浏览器'))
ui6B = tk.Button(root, text='在已经执行命令“选择/打开”的情况下，打开应用：资源管理器', command=lambda:pyperclip.copy('资源管理器'))
ui1C = tk.Button(root, text='在打开资源管理器的情况下，打开C:/下的“SOPXS”文件', command=lambda:pyperclip.copy('SOPXS'))
ui2C = tk.Button(root, text='在打开资源管理器的情况下，打开C:/下的“help”文件', command=lambda:pyperclip.copy('Help'))
ui3C = tk.Button(root, text='在打开资源管理器的情况下，打开C:/下的“help.txt”文件', command=lambda:pyperclip.copy('help.txt'))
ui1D = tk.Button(root, text='安装扩展插件应用sopXseerror_exe_eerror.exe（有风险）', command=lambda:pyperclip.copy('安装扩展插件应用sopXseerror_exe_eerror.exe'))
ui2D = tk.Button(root, text='系统命令帮助', command=lambda:pyperclip.copy('系统命令帮助'))
label = tk.Label(root, text="点击中间按钮复制对应命令", font=("Arial", 10))
label.place(x=115, y=200)
root.mainloop()